UNDO ME BUILD LEAN FRAMEWORK
[ci skip]

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -235,18 +235,18 @@ jobs:
           echo "mount_point=${mount_point}">>$GITHUB_OUTPUT
       - name: 'Verify presence of optional frameworks'
         run: |
-          OPTIONAL_FRAMEWORKS="avif jxl webp"
-          rc=0
-          for opt in $OPTIONAL_FRAMEWORKS; do
-            fw_path="${{ steps.mount.outputs.mount-point }}/optional/${opt}.xcframework"
-            if [ -d "${fw_path}" ]; then
-              echo "$fw_path OK"
-            else
-              echo "$fw_path MISSING"
-              rc=1
-            fi
-          done
-          exit $rc
+          #OPTIONAL_FRAMEWORKS="avif jxl webp"
+          #rc=0
+          #for opt in $OPTIONAL_FRAMEWORKS; do
+          #  fw_path="${{ steps.mount.outputs.mount-point }}/optional/${opt}.xcframework"
+          #  if [ -d "${fw_path}" ]; then
+          #    echo "$fw_path OK"
+          #  else
+          #    echo "$fw_path MISSING"
+          #    rc=1
+          #  fi
+          #done
+          #exit $rc
       - name: 'CMake (configure + build) Darwin'
         run: |
           set -e
